server {
    listen 80;
    listen [::]:80;
    server_name @SERVER_NAME@;

    location ^~ /.well-known/acme-challenge/ {
        root @ACME_ROOT@;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name @SERVER_NAME@;

    ssl_certificate @CERT_DIR@/fullchain.pem;
    ssl_certificate_key @CERT_DIR@/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    auth_basic "CloudWatcher";
    auth_basic_user_file @HTPASSWD@;

    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        root @ACME_ROOT@;
    }

    location / {
        proxy_pass http://@WEB_HOST@:@WEB_PORT@;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
