server {
    listen 80;
    listen [::]:80;
    server_name @SERVER_NAME@;

    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        root @ACME_ROOT@;
    }

    auth_basic "CloudWatcher";
    auth_basic_user_file @HTPASSWD@;

    location / {
        proxy_pass http://@WEB_HOST@:@WEB_PORT@;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
